workflows:
  flutter-android-workflow: # اسم سير العمل
    name: Flutter Android Build # اسم وصفي
    max_build_duration: 120 # الحد الأقصى لمدة البناء (بالدقائق)
    instance_type: mac_mini_m2 # نوع الجهاز (Mac Mini M2)
    environment: # الإعدادات البيئية
      flutter: stable # إصدار Flutter
      vars: # متغيرات بيئية
        API_KEY: "$API_KEY" # مفتاح API (يُضاف في Codemagic)
        BACKEND_URL: "$BACKEND_URL" # عنوان واجهة المستخدم الخلفية
    scripts: # النصوص البرمجية
      - name: Get Flutter Dependencies
        script: flutter pub get # تثبيت التبعيات
      - name: Run Tests
        script: flutter test # تشغيل الاختبارات
        ignore_failure: true # الاستمرار حتى لو فشلت الاختبارات
      - name: Build APK
        script: flutter build apk --release # بناء APK
      - name: Rename APK
        script: mv build/app/outputs/flutter-apk/app-release.apk dhikr-compass-pro.apk # إعادة تسمية الـ APK
    artifacts: # الملفات الناتجة
      - dhikr-compass-pro.apk # حفظ ملف APK باسم مخصص
    publishing: # النشر (اختياري)
      email: # إرسال إشعار عبر البريد
        recipients:
          - dr.remo.hisham.1@gmail.com # استبدل بالبريد الإلكتروني الخاص بك